spring.application.name=BootMSProj01-EurekaServer

#Eureka Server port
server.port=8761

#Disable two properties inherited from parent project
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

