spring.application.name=BootMSProj03-EurekaServer

#Port number
server.port=8761

#Disable the default inherited from parent project
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
