spring.application.name=BootMSProj02-WishMS

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Register with Eureka serverlos
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#MS port
server.port=9092
