spring.application.name=CartMS

#MS port
server.port=6061

#Register with Eureka serverlos
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Get more details from health actuator
#management.endspoint.health.show-details=always

#Deactivate health actuator
#management.endpoint.health.access=none

#Activate health,info actuators
#management.endpoints.web.exposure.include=health,info

#Activate All actuators
management.endpoints.web.exposure.include=*

#Activate shutdown actuator
management.endpoint.shutdown.access=unrestricted

management.endpoint.info.access=none


#Get more details from health actuator
management.info.env.enabled=true

#Project information
info.add.name=OpenFx
info.app.size=100
info.app.addrs=hyd
info.app.lead=raja 
