spring.application.name=BillingMS

#instance id
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}

#MS port
server.port=9092

#Register with Eureka serverlos
eureka.client.service-url.default-zone=http://localhost:8761/eureka